#!/bin/bash

aglio -i "index.md" -o "index.html"

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
/etc/init.d/apache2 start
cp -rf /api/* /var/www/html/
node
